import { useState } from 'react';
import { FieldsType, FieldType, KeyboardType } from '../types/Types';

const FilterOptionsFields = () => {
  const [fields, setFields] = useState<FieldsType[]>([
    {
      name: "category",
      type: FieldType.SELECT,
      placeHolder: "Select Category",
      label: "Category",
      error: false,
      value: "",
      required: true,
      keyboard: KeyboardType.DEFAULT,
      options: [
        { label: "options 1", value: "options 1" },
        { label: "options 2", value: "options 2" },
        { label: "options 3", value: "options 3" }
      ]
    },
     {
      name: "to_be_done",
      type: FieldType.SELECT,
      placeHolder: "Select To be done",
      label: "To be done",
      error: false,
      value: "",
      required: true,
      keyboard: KeyboardType.DEFAULT,
      options: [
        { label: "options 1", value: "options 1" },
        { label: "options 2", value: "options 2" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
        { label: "options 3", value: "options 3" },
      ]
    },
    {
      name: "work_location",
      type: FieldType.STRING,
      placeHolder: "Work location",
      label: "Work location",
      error: false,
      value: "",
      required: true,
      keyboard: KeyboardType.DEFAULT,
    },
    {
      name: "distance_range",
      type: FieldType.RANGE,
      placeHolder: "Distance Range",
      label: "Distance Range",
      error: false,
      value: "",
      required: true,
      keyboard: KeyboardType.DEFAULT,
      max: 100,
      min: 0,
      step: 1,
    },
    {
      name: "price_range",
      type: FieldType.RANGE,
      placeHolder: "Price Range",
      label: "Price Range",
      error: false,
      value: "",
      required: true,
      keyboard: KeyboardType.DEFAULT,
      max: 100,
      min: 0,
      step: 1,
      range: true,
    },
    {
      name: "sort",
      type: FieldType.SELECT,
      placeHolder: "Sort By",
      label: "Sort By",
      error: false,
      value: "",
      required: true,
      keyboard: KeyboardType.DEFAULT,
      options: [
        { label: "Newest First", value: "Newest First" },
        { label: "Oldest First", value: "Oldest First" },
        { label: "Open for Bid", value: "Open for Bid" },
        { label: "Assigned", value: "Assigned" },
      ]
    },
  ]);
  return { fields, setFields };
};


export default FilterOptionsFields
